import Foundation

enum RecipeCatalog {
    static func load(bundle: Bundle = .main) throws -> [RecipeKind: [String]] {
        var result: [RecipeKind: [String]] = [:]
        for kind in RecipeKind.allCases {
            let resource = kind == .cooking ? "cookingrecipes" : "craftingrecipes"
            guard let url = bundle.url(forResource: resource, withExtension: "json") else {
                throw ItemCatalogError.resourceMissing
            }
            let data = try Data(contentsOf: url)
            result[kind] = try JSONDecoder().decode([String].self, from: data)
        }
        return result
    }

    static func localizedName(for key: String) -> String {
        chineseNames[key] ?? ItemCatalog.chineseNames[key] ?? key
    }

    static func hasChineseName(for key: String) -> Bool {
        chineseNames[key] != nil || ItemCatalog.chineseNames[key] != nil
    }

    // Names mirror the Simplified Chinese terminology used by the 1.6 data set.
    // Unknown mod recipes intentionally keep their original key.
    static let chineseNames: [String: String] = [
        // Cooking
        "Fried Egg": "煎鸡蛋",
        "Omelet": "煎蛋卷",
        "Salad": "沙拉",
        "Cheese Cauli.": "乳酪花椰菜",
        "Baked Fish": "烤鱼",
        "Parsnip Soup": "防风草汤",
        "Vegetable Stew": "蔬菜杂烩",
        "Complete Breakfast": "完美早餐",
        "Fried Calamari": "炸鱿鱼",
        "Strange Bun": "奇怪的小面包",
        "Lucky Lunch": "幸运午餐",
        "Fried Mushroom": "炒蘑菇",
        "Pizza": "披萨",
        "Bean Hotpot": "豆类火锅",
        "Glazed Yams": "琉璃山药",
        "Carp Surprise": "惊喜鲤鱼",
        "Hashbrowns": "薯饼",
        "Pancakes": "薄煎饼",
        "Salmon Dinner": "鲑鱼晚餐",
        "Fish Taco": "鱼肉卷",
        "Crispy Bass": "香酥鲈鱼",
        "Pepper Poppers": "爆炒青椒",
        "Bread": "面包",
        "Tom Kha Soup": "椰汁汤",
        "Trout Soup": "鳟鱼汤",
        "Chocolate Cake": "巧克力蛋糕",
        "Pink Cake": "粉红蛋糕",
        "Rhubarb Pie": "大黄派",
        "Cookies": "饼干",
        "Spaghetti": "意大利面",
        "Fried Eel": "炒鳗鱼",
        "Spicy Eel": "香辣鳗鱼",
        "Sashimi": "生鱼片",
        "Maki Roll": "生鱼寿司",
        "Tortilla": "墨西哥薄饼",
        "Red Plate": "红之盛宴",
        "Eggplant Parm.": "帕尔玛奶酪茄子",
        "Rice Pudding": "大米布丁",
        "Ice Cream": "冰淇淋",
        "Blueberry Tart": "蓝莓千层酥",
        "Autumn's Bounty": "秋日恩赐",
        "Pumpkin Soup": "南瓜汤",
        "Super Meal": "巨无霸餐",
        "Cran. Sauce": "红莓酱",
        "Stuffing": "塞料面包",
        "Farmer's Lunch": "农夫午餐",
        "Survival Burger": "救生汉堡",
        "Dish o' The Sea": "海之菜肴",
        "Miner's Treat": "矿工特供",
        "Roots Platter": "块茎拼盘",
        "Algae Soup": "海藻汤",
        "Pale Broth": "清汤",
        "Plum Pudding": "葡萄干布丁",
        "Artichoke Dip": "水煮洋蓟",
        "Stir Fry": "蔬菜什锦盖饭",
        "Roasted Hazelnuts": "烤榛子",
        "Pumpkin Pie": "南瓜派",
        "Radish Salad": "萝卜沙拉",
        "Fruit Salad": "水果沙拉",
        "Blackberry Cobbler": "黑莓脆皮饼",
        "Cranberry Candy": "蔓越莓糖果",
        "Bruschetta": "意式烤面包",
        "Coleslaw": "卷心菜沙拉",
        "Fiddlehead Risotto": "意式蕨菜炖饭",
        "Poppyseed Muffin": "虞美人籽松糕",
        "Chowder": "海鲜杂烩汤",
        "Lobster Bisque": "龙虾浓汤",
        "Fish Stew": "烩鱼汤",
        "Escargot": "法式田螺",
        "Maple Bar": "枫糖棒",
        "Crab Cakes": "蟹黄糕",
        "Triple Shot Espresso": "三倍浓缩咖啡",
        "Shrimp Cocktail": "虾鸡尾酒",
        "Seafoam Pudding": "海泡布丁",
        "Ginger Ale": "姜汁汽水",
        "Banana Pudding": "香蕉布丁",
        "Mango Sticky Rice": "芒果糯米饭",
        "Poi": "夏威夷芋泥",
        "Tropical Curry": "热带咖喱",
        "Squid Ink Ravioli": "墨汁意大利饺",
        "Moss Soup": "苔藓汤",

        // Crafting
        "Wood Fence": "木围栏",
        "Stone Fence": "石围栏",
        "Iron Fence": "铁围栏",
        "Hardwood Fence": "硬木围栏",
        "Grass Starter": "草籽",
        "Blue Grass Starter": "蓝色草籽",
        "Gate": "大门",
        "Chest": "木箱",
        "Big Chest": "大箱子",
        "Stone Chest": "石箱",
        "Big Stone Chest": "石制大箱子",
        "Torch": "火把",
        "Scarecrow": "稻草人",
        "Deluxe Scarecrow": "豪华稻草人",
        "Bee House": "蜂房",
        "Keg": "小桶",
        "Cask": "木桶",
        "Dehydrator": "烘干机",
        "Furnace": "熔炉",
        "Heavy Furnace": "重型熔炉",
        "Anvil": "铁砧",
        "Mini-Forge": "迷你锻造台",
        "Garden Pot": "花盆",
        "Wood Sign": "木牌",
        "Stone Sign": "石牌",
        "Dark Sign": "深色牌子",
        "Text Sign": "文字标牌",
        "Cheese Press": "压酪机",
        "Mayonnaise Machine": "蛋黄酱机",
        "Seed Maker": "种子生产器",
        "Loom": "织布机",
        "Oil Maker": "产油机",
        "Recycling Machine": "回收机",
        "Worm Bin": "虫饵盒",
        "Deluxe Worm Bin": "高级虫饵盒",
        "Bait Maker": "鱼饵制造机",
        "Fish Smoker": "熏鱼机",
        "Preserves Jar": "罐头瓶",
        "Charcoal Kiln": "煤炭窑",
        "Tapper": "树液采集器",
        "Mushroom Log": "蘑菇树桩",
        "Lightning Rod": "避雷针",
        "Slime Incubator": "史莱姆孵化器",
        "Slime Egg-Press": "史莱姆压蛋器",
        "Crystalarium": "宝石复制机",
        "Mini-Jukebox": "迷你点唱机",
        "Sprinkler": "洒水器",
        "Quality Sprinkler": "优质洒水器",
        "Iridium Sprinkler": "铱制洒水器",
        "Staircase": "楼梯",
        "Flute Block": "长笛块",
        "Drum Block": "鼓块",
        "Basic Fertilizer": "初级肥料",
        "Tree Fertilizer": "树肥",
        "Mystic Tree Seed": "神秘树种",
        "Quality Fertilizer": "高级肥料",
        "Basic Retaining Soil": "初级保湿土壤",
        "Quality Retaining Soil": "高级保湿土壤",
        "Speed-Gro": "生长激素",
        "Deluxe Speed-Gro": "高级生长激素",
        "Hyper Speed-Gro": "顶级生长激素",
        "Deluxe Fertilizer": "顶级肥料",
        "Deluxe Retaining Soil": "顶级保湿土壤",
        "Cherry Bomb": "樱桃炸弹",
        "Bomb": "炸弹",
        "Mega Bomb": "超级炸弹",
        "Explosive Ammo": "爆炸弹丸",
        "Transmute (Fe)": "铁锭",
        "Transmute (Au)": "金锭",
        "Ancient Seeds": "古代种子",
        "Wild Seeds (Sp)": "春季种子",
        "Wild Seeds (Su)": "夏季种子",
        "Wild Seeds (Fa)": "秋季种子",
        "Wild Seeds (Wi)": "冬季种子",
        "Fiber Seeds": "纤维种子",
        "Tea Sapling": "茶苗",
        "Warp Totem: Farm": "传送图腾：农场",
        "Warp Totem: Mountains": "传送图腾：山岭",
        "Warp Totem: Beach": "传送图腾：海滩",
        "Warp Totem: Desert": "传送图腾：沙漠",
        "Warp Totem: Island": "传送图腾：姜岛",
        "Rain Totem": "雨水图腾",
        "Treasure Totem": "宝藏图腾",
        "Cookout Kit": "野炊工具",
        "Tent Kit": "便携帐篷",
        "Field Snack": "工作小食",
        "Statue Of Blessings": "祝福雕像",
        "Statue Of The Dwarf King": "矮人之王雕像",
        "Jack-O-Lantern": "南瓜灯",
        "Wood Floor": "木地板",
        "Straw Floor": "稻草地板",
        "Weathered Floor": "风化地板",
        "Rustic Plank Floor": "乡村木地板",
        "Crystal Floor": "水晶地板",
        "Stone Floor": "石头地板",
        "Stone Walkway Floor": "石制走道地板",
        "Brick Floor": "红砖地板",
        "Wood Path": "木头小径",
        "Gravel Path": "砾石小径",
        "Cobblestone Path": "鹅卵石小径",
        "Stepping Stone Path": "垫脚石小径",
        "Crystal Path": "水晶小径",
        "Bait": "鱼饵",
        "Deluxe Bait": "高级鱼饵",
        "Wild Bait": "万能鱼饵",
        "Challenge Bait": "挑战鱼饵",
        "Magnet": "磁铁",
        "Spinner": "旋式鱼饵",
        "Dressed Spinner": "精装旋式鱼饵",
        "Trap Bobber": "陷阱浮标",
        "Sonar Bobber": "声纳浮漂",
        "Cork Bobber": "软木塞浮标",
        "Treasure Hunter": "寻宝者",
        "Barbed Hook": "倒刺钩",
        "Oil Of Garlic": "蒜油",
        "Life Elixir": "生命药水",
        "Crab Pot": "蟹笼",
        "Iridium Band": "铱环",
        "Wedding Ring": "结婚戒指",
        "Ring of Yoba": "由巴的戒指",
        "Sturdy Ring": "结实戒指",
        "Warrior Ring": "战士戒指",
        "Tub o' Flowers": "一簇鲜花",
        "Wooden Brazier": "木头火炬",
        "Wicked Statue": "邪恶雕像",
        "Stone Brazier": "石头火炬",
        "Gold Brazier": "金制火炬",
        "Campfire": "篝火",
        "Stump Brazier": "树桩火炬",
        "Carved Brazier": "镂空火炬",
        "Skull Brazier": "骷髅火炬",
        "Barrel Brazier": "木桶火炬",
        "Marble Brazier": "大理石火炬",
        "Wood Lamp-post": "木灯柱",
        "Iron Lamp-post": "铁灯柱",
        "Fairy Dust": "仙尘",
        "Bug Steak": "虫肉块",
        "Quality Bobber": "优质浮标",
        "Monster Musk": "怪兽香水",
        "Mini-Obelisk": "迷你图腾尖塔",
        "Farm Computer": "农场电脑",
        "Ostrich Incubator": "鸵鸟孵化器",
        "Geode Crusher": "晶球破开器",
        "Solar Panel": "太阳能板",
        "Bone Mill": "碎骨机",
        "Thorns Ring": "荆棘戒指",
        "Glowstone Ring": "辉石戒指",
        "Heavy Tapper": "重型树液采集器",
        "Hopper": "加料器",
        "Magic Bait": "魔法鱼饵"
    ]
}
